on:
  release:
    types:
      - published

name: Push to Godot Asset Library

jobs:
  publish:
    # TODO: Add assetId below, then enable
    if: false
    runs-on: ubuntu-latest
    name: Push new release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Push to Godot Asset Library
        uses: deep-entertainment/godot-asset-lib-action@v0.6.0
        with:
          username: ${{ secrets.GODOT_ASSET_LIBRARY_USERNAME }}
          password: ${{ secrets.GODOT_ASSET_LIBRARY_PASSWORD }}
          assetId: TODO
          assetTemplate: asset-template.json.hb
